### ISSUE TITLE
What encoding?

### ISSUE THREAD

**Issue by pevel-dev** [bkerler/opencl_brute#9]
If 

 `# -*- coding: utf-8 -*- 
#!/usr/bin/python3
import sys
import hashlib
import functools, operator
from Library import opencl
from Library.opencl_information import opencl_information
import numpy

def sha256_test(opencl_algo, passwordlist):
    print("Testing sha256 ..")
    ctx=opencl_algo.cl_sha256_init()
    clresult=opencl_algo.cl_sha256(ctx,passwordlist)
    return clresult 

def main(argv):
    if (len(argv)<2):
        print("Implementation tests")
        print("-----------------------------------------------------------------")
        info=opencl_information()
        info.printplatforms()
        print("\nPlease run as: python test.py [platform number]")
        return

    # Input values to be hashed
    hash = b"89619fc70bfc7da0ede567e8e3266261d4c46b5fb35247dac53894b8875130cc"

    platform = int(argv[1])
    debug = 0
    write_combined_file = False
    opencl_algos = opencl.opencl_algos(platform, debug, write_combined_file,inv_memory_density=1)
    
    # Call the tests
    s = sha256_test(opencl_algos, [hash])
    s = s[0]
    print(s)

    print(s.hexdigest()) # Error!
    
    
    
'if __name__ == '__main__':
  main(sys.argv)`'

**I get print b'\x01\x029HI\x8ae\xf1(1S\xa9!\x15\x1d\x80uP\x1c\xc1\xdc*\x9a\xa8\xab\xb1\xe7\x94\x84\x81:\xe9'
 And trace AttributeError: 'bytes' object has no attribute 'hexdigest'
 How to decrypt given bytes into a hash like in hashlib?
.decode() Also does not work - Not suitable encoding**

**Comment by bkerler** [comment]
Sorry, this is no issue of my tool, but python knowledge issue. 

Use binascii.hexlify to convert a byte string to hex string and binascii.unhexlify to convert from a hex string to a byte string. 

hash = b"89619fc70bfc7da0ede567e8e3266261d4c46b5fb35247dac53894b8875130cc"
obviously isn't right. I think you want  hash=binascii.unhexlify("8961....30cc") instead. and then instead of print(s), you should do print(binascii.hexlify(s).decode('utf-8')).
